// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq6wu7qb6AmulE5TVoutK-rFlnKqcfYnk',
    appId: '1:974630074811:web:21911994e8a55281f1ec9e',
    messagingSenderId: '974630074811',
    projectId: 'shieldy-6e7a5',
    authDomain: 'shieldy-6e7a5.firebaseapp.com',
    storageBucket: 'shieldy-6e7a5.appspot.com',
    measurementId: 'G-KQX70ZE5X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb2lej30EyZzLB8FIIWE6ZvrO9auCV6d8',
    appId: '1:974630074811:android:a80017f99b6915d3f1ec9e',
    messagingSenderId: '974630074811',
    projectId: 'shieldy-6e7a5',
    storageBucket: 'shieldy-6e7a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXJnUiW-f6QIhIxBdRe-PgZ_H1vD7sy8Y',
    appId: '1:974630074811:ios:3cb6937f9e09e7b6f1ec9e',
    messagingSenderId: '974630074811',
    projectId: 'shieldy-6e7a5',
    storageBucket: 'shieldy-6e7a5.appspot.com',
    iosBundleId: 'com.example.shieldy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXJnUiW-f6QIhIxBdRe-PgZ_H1vD7sy8Y',
    appId: '1:974630074811:ios:7b2a4299c63c4846f1ec9e',
    messagingSenderId: '974630074811',
    projectId: 'shieldy-6e7a5',
    storageBucket: 'shieldy-6e7a5.appspot.com',
    iosBundleId: 'com.example.shieldy.RunnerTests',
  );
}
